name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  webapp_test:
    defaults:
      run:
        working-directory: ./webapp

    name: Run Tests (Webapp)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Linter
        run: yarn lint
      
  backend_test:
    defaults:
      run:
        working-directory: ./backend

    name: Run Tests (Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint
